name = "LaplaceInterpolation"
uuid = "afb1b68e-e51f-4e49-a799-0e085170423d"
authors = ["Charlotte Haley <haleycharlotte@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
ThinPlateSplines = "1d861738-f48e-4029-b1d3-81ce6bc7f5ab"
